name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Repozitoriy kodini checkout qilish
      - name: Checkout code
        uses: actions/checkout@v4

      # Java va Gradle sozlash
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle cache’ni sozlash (build tezligi uchun)
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Loyihani build qilish
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # Docker imagelarini qurish va serverga ko‘chirish
      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # SSH kalitini vaqtincha faylga yozish
          echo "$SSH_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem

          # EC2 serverda app direktoriyasini yaratish
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
            mkdir -p /home/${EC2_USER}/app
          EOF

          # Loyiha fayllarini EC2 serverga ko‘chirish
          scp -o StrictHostKeyChecking=no -i ssh_key.pem -r ./* ${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/app/

          # EC2 serverda Docker va Docker Compose o‘rnatish (agar o‘rnatilmagan bo‘lsa)
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
            # Docker o‘rnatish
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ${EC2_USER}
            fi

            # Docker Compose o‘rnatish
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Docker Compose bilan deploy qilish
            cd /home/${EC2_USER}/app
            docker-compose down
            docker-compose up -d --build
          EOF

          # Vaqtincha SSH kalitini o‘chirish
          rm ssh_key.pem
